spring.application.name=tevcol-backend
spring.datasource.url=jdbc:mariadb://localhost:3307/dbtevcol
spring.datasource.username=stevan
spring.datasource.password=Liga19302230969696

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
